repos:
  - repo: https://github.com/rubocop/rubocop
    rev: v1.57.0
    hooks:
      - id: rubocop
        args: [--auto-correct]

  - repo: local
    hooks:
      - id: gts-lint
        name: gts-lint
        entry: npx gts lint
        language: system
        types: [ts]
        stages: [commit]
